language: php

php:
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

notifications:
  email:
    recipients:
      - wolters.fl@gmail.com
    on_success: change
    on_failure: always
